### PR TITLE
ZF3 support added

### PR DESCRIPTION
**Pull request by xl32**
ZF3 got rid of service manager in controllers, so I've added swagger setter to docs controller.

### CODE REVIEW

**Comment by davidwindell** [comment]
Thanks @xl32, can you create a factory class please instead of using closures?

**Comment by xl32** [comment]
Done, added. Please check.

**Comment by davidwindell** [comment]
:+1: Merged, thanks again @xl32

**Comment by davidwindell** [comment]
Released as `2.1.1`

**Pull request merged**
